/* List of types of action */
export const INITIAL_STATE = 'INITIAL_STATE';
export const TODO_REQUEST = 'TODO_REQUEST';
export const TODO_REQUEST_FAILURE = 'TODO_REQUEST_FAILURE';

export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const COMPLETE_TODO_SUCCESS = 'COMPLETE_TODO_SUCCESS'

